$(document).ready(function () {
  $('.main-restaurant-slider').slick({
    arrows: true,
    slidesToShow: 2,
    speed: 500,
    easing: 'easy',
    infinite: false,
    initialSlide: 0,
    autoplay: false,
    pauseOnHover: true,
    pauseOnFocus: true,
    draggable: true,
    swipe: true,
    touchThreshold: 5,
    touchMove: true,
    mobileFirst: true,
    waitForAnimate: true,
    variableWidth: true,
    centerMode: false,
    responsive: [
      {
        breakpoint: 1439,
        settings: { slidesToShow: 5 },
      },
    ],
  });
  $('.main-hotel-slider').slick({
    arrows: true,
    slidesToShow: 2,
    speed: 500,
    easing: 'easy',
    infinite: false,
    initialSlide: 0,
    autoplay: false,
    pauseOnHover: true,
    pauseOnFocus: true,
    draggable: true,
    swipe: true,
    touchThreshold: 5,
    touchMove: true,
    mobileFirst: true,
    waitForAnimate: true,
    variableWidth: true,
    centerMode: false,
  });
  $('.hotel-hero-slider').slick({
    arrows: true,
    slidesToShow: 2,
    speed: 500,
    easing: 'easy',
    infinite: false,
    initialSlide: 0,
    autoplay: false,
    pauseOnHover: true,
    pauseOnFocus: true,
    draggable: true,
    swipe: true,
    touchThreshold: 5,
    touchMove: true,
    mobileFirst: true,
    waitForAnimate: true,
    variableWidth: true,
    centerMode: false,
  });
  $('.restaurant-hero-slider').slick({
    arrows: true,
    slidesToShow: 2,
    speed: 500,
    easing: 'easy',
    infinite: false,
    initialSlide: 0,
    autoplay: false,
    pauseOnHover: true,
    pauseOnFocus: true,
    draggable: true,
    swipe: true,
    touchThreshold: 5,
    touchMove: true,
    mobileFirst: true,
    waitForAnimate: true,
    variableWidth: true,
    centerMode: false,
  });
  $('.restaurant-menu-slider').slick({
    arrows: true,
    slidesToShow: 2,
    speed: 500,
    easing: 'easy',
    infinite: false,
    initialSlide: 0,
    autoplay: false,
    pauseOnHover: true,
    pauseOnFocus: true,
    draggable: true,
    swipe: true,
    touchThreshold: 5,
    touchMove: true,
    mobileFirst: true,
    waitForAnimate: true,
    variableWidth: true,
    centerMode: false,
  });
  $('.room-hero-slider').slick({
    arrows: true,
    slidesToShow: 2,
    speed: 500,
    easing: 'easy',
    infinite: false,
    initialSlide: 0,
    autoplay: false,
    pauseOnHover: true,
    pauseOnFocus: true,
    draggable: true,
    swipe: true,
    touchThreshold: 5,
    touchMove: true,
    mobileFirst: true,
    waitForAnimate: true,
    variableWidth: true,
    centerMode: false,
  });
});
